### ISSUE TITLE
Github profile is looking empty. Add some information.

### ISSUE THREAD

**Issue by vikasganiga05** [dhvakr/dhvakr#1]
Hi @dhvakr , your Github profile is looking empty. add some basic info about you and what you do?
So the other developers know about yourself :slightly_smiling_face: 

#### Example
- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

**Comment by dhvakr** [comment]
Definitely i'll make it within a week ...am working on it with some unique way of presentation !! Please check back u definitely like it ....

**Comment by vikasganiga05** [comment]
> Definitely i'll make it within a week vikas ...am working on it with some unique way of presentation !! Please check back u definitely like it ....

Oh! that's nice, I will definitely look at it in the future.

**Comment by vikasganiga05** [comment]
Hey @dhvakr , If you want to close this issue you can :slightly_smiling_face:

**Comment by vikasganiga05** [comment]
> > Definitely i'll make it within a week vikas ...am working on it with some unique way of presentation !! Please check back u definitely like it ....
> 
> Oh! that's nice, I will definitely look at it in the future. I am also decided to update mine.
